name: 'Build docker image'
on:
  workflow_dispatch:
    inputs:
      dockerfilepath:
        description: 'Path to the dockerfile'
        required: true
      version:
        description: 'Version to push'
        required: true
        default: "v1.0"
jobs:
  build-push-linux-multi:
    name: Build & push linux/amd64 and linux/arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm,amd64

      - name: Registry Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ${{ github.event.inputs.dockerfilepath }}
          tags: |
            quay.io/mickkael/${{ github.event.inputs.dockerfilepath }}:${{ github.event.inputs.version }}
            quay.io/mickkael/${{ github.event.inputs.dockerfilepath }}:latest